# Makefile for check_reflectance project

TARGET=check_reflectance
CXX=cl
CCFLAGS=/EHsc /I"$(QGIS_HOME)\include"
GDAL_LIB="$(QGIS_HOME)\lib\gdal_i.lib"
CLEAN=del /Q

all: $(TARGET).exe

$(TARGET).exe: $(TARGET).obj
	$(CXX) /Fe..\..\bin\$(TARGET).exe ..\..\obj\$(TARGET).obj $(GDAL_LIB) /link && del ..\..\bin\*.exp && del ..\..\bin\*.lib

$(TARGET).obj: $(TARGET).cpp
	$(CXX) $(CCFLAGS) /Fo..\..\obj\$(TARGET).obj /c $(TARGET).cpp

clean:
	$(CLEAN) ..\..\obj\*
	$(CLEAN) ..\..\bin\$(TARGET).exe
