# Makefile for check_reflectance project

TARGET=check_reflectance
CXX=g++
CCFLAGS=-Wall -Wno-unused-result -I/usr/include/gdal
# -I${RSUTILS_HOME}/include
LDFLAGS=-lgdal -ltiff
CLEAN=rm -f

all: $(TARGET)

$(TARGET): $(TARGET).o
	$(CXX) -o ../../bin/$(TARGET) ../../obj/$(TARGET).o $(LDFLAGS)

$(TARGET).o: $(TARGET).cpp
	$(CXX) $(CCFLAGS) -o ../../obj/$(TARGET).o -c $(TARGET).cpp

clean:
	$(CLEAN) ../../obj/*.o ../../bin/$(TARGET)
