# Makefile for PROGRAM__NAME project

TARGET=PROGRAM__NAME
CXX=clang++
CCFLAGS=-Wall -I/usr/local/include
LDFLAGS=-L/usr/local/lib -lgdal
CLEAN=rm -f

all: $(TARGET)

$(TARGET): $(TARGET).o
	$(CXX) $(LDFLAGS) -o ../../bin/$(TARGET) ../../objects/$(TARGET).o

$(TARGET).o: $(TARGET).cpp
	$(CXX) $(CCFLAGS) -o ../../objects/$(TARGET).o -c $(TARGET).cpp

clean:
	$(CLEAN) ../../objects/*.o ../../bin/$(TARGET)
