# Makefile for PROGRAM__NAME project

TARGET=PROGRAM__NAME
CXX=mingw32-g++
CCFLAGS=-I"$(QGIS_HOME)\include"
GDAL_LIB="$(QGIS_HOME)\lib\gdal_i.lib"
CLEAN=del /Q

all: $(TARGET).exe

$(TARGET).exe: $(TARGET).obj
	$(CXX) -o ..\..\bin\$(TARGET).exe ..\..\obj\$(TARGET).obj $(GDAL_LIB)

$(TARGET).obj: $(TARGET).cpp
	$(CXX) $(CCFLAGS) -o ..\..\obj\$(TARGET).obj -c $(TARGET).cpp

clean:
	$(CLEAN) ..\..\obj\*
	$(CLEAN) ..\..\bin\$(TARGET).exe
