# Makefile for check_reflectance project

PROG_NAME=s2_utm_tile_finder
SRC_FILES=s2_utm_tile_finder.cpp
OBJ_FILES=s2_utm_tile_finder.o
CXX=clang++
CCFLAGS=-Wall
CLEAN=rm -f

all: $(PROG_NAME)

$(PROG_NAME): $(OBJ_FILES)
	cd .. ; $(CXX) -o ../../binary/target/$(PROG_NAME) ./obj/$(OBJ_FILES)

$(OBJ_FILES): $(SRC_FILES)
	cd .. ; $(CXX) $(CCFLAGS) -o ./obj/$(OBJ_FILES) -c $(SRC_FILES)

clean:
	cd .. ; $(CLEAN) ./obj/*.o *~ ../../binary/target/$(PROG_NAME)
