# Makefile for check_reflectance project

PROG_NAME=s2_utm_tile_finder.exe
SRC_FILES=s2_utm_tile_finder.cpp
OBJ_FILES=s2_utm_tile_finder.obj
CXX=cl
CLEAN=del /Q

all: $(PROG_NAME)

$(PROG_NAME): $(OBJ_FILES)
	$(CXX) /Fe..\..\binary\target\$@ obj\$** /link /MACHINE:X64 && del ..\..\binary\target\*.exp && del ..\..\binary\target\*.lib

$(OBJ_FILES): $(SRC_FILES)
	$(CXX) /Foobj\$@ /c $**

clean:
	$(CLEAN) obj\* 
	$(CLEAN) ..\..\binary\target\$(PROG_NAME)
