# Makefile for check_reflectance project

PROG_NAME=s2_utm_tile_finder
SRC_FILES=s2_utm_tile_finder.cpp
OBJ_FILES=s2_utm_tile_finder.o
CXX=g++
CCFLAGS=-Wall
CLEAN=rm -f

all: $(PROG_NAME)

$(PROG_NAME): $(OBJ_FILES)
	$(CXX) -o ../../binary/target/$@ ./obj/$^

$(OBJ_FILES): $(SRC_FILES)
	$(CXX) $(CCFLAGS) -o ./obj/$@ -c $^

clean:
	$(CLEAN) ./obj/*.o *~ ../../binary/target/$(PROG_NAME)
