MAKE_FILE=-f makefile.mac

all:	s2_set_projection check_reflectance

clean: 
	cd ./source/s2_set_projection && $(MAKE) $(MAKE_FILE) clean
	cd ./source/check_reflectance && $(MAKE) $(MAKE_FILE) clean

s2_set_projection: 
	cd ./source/s2_set_projection && $(MAKE) $(MAKE_FILE) all

check_reflectance: 
	cd ./source/check_reflectance && $(MAKE) $(MAKE_FILE) all
