# Makefile for PROGRAM__NAME project

TARGET=PROGRAM__NAME
CXX=g++
CCFLAGS=-Wall
CLEAN=rm -f

all: $(TARGET)

$(TARGET): $(TARGET).o
	$(CXX) -o ../../bin/$(TARGET) ../../obj/$(TARGET).o

$(TARGET).o: $(TARGET).cpp
	$(CXX) $(CCFLAGS) -o ../../obj/$(TARGET).o -c $(TARGET).cpp

clean:
	$(CLEAN) ../../obj/*.o ../../bin/$(TARGET)
