# Makefile for PROGRAM__NAME project

TARGET=PROGRAM__NAME
CXX=cl
CLEAN=del /Q

all: $(TARGET).exe

$(TARGET).exe: $(TARGET).obj
	$(CXX) /Fe..\..\bin\$(TARGET).exe ..\..\obj\$(TARGET).obj /link

$(TARGET).obj: $(TARGET).cpp
	$(CXX) /Fo..\..\obj\$(TARGET).obj /c $(TARGET).cpp

clean:
	$(CLEAN) ..\..\obj\*
	$(CLEAN) ..\..\bin\$(TARGET).exe
